#include "Config.h"

// ===== DEFINIZIONI CONFIGURAZIONE ACCESS POINT =====
const char* DEFAULT_AP_SSID = "SmartHome-Access-Point";
const char* DEFAULT_AP_PASSWORD = "123456789";

// ===== DEFINIZIONI CONFIGURAZIONE BOTTONI PERSONALIZZATI =====
const char* CUSTOM_BUTTONS_PREF_NAMESPACE = "buttons";